#!/usr/bin/env python3
"""
Build Script - Compiles partials into a single HTML file
This creates index-standalone.html that can be opened directly in a browser
"""

import os
import re

def read_file(filepath):
    """Read file content"""
    with open(filepath, 'r', encoding='utf-8') as f:
        return f.read()

def build_standalone():
    """Build standalone HTML file with inlined partials"""
    
    print("🔨 Building standalone HTML...")
    
    # Read the main index.html
    index_content = read_file('index.html')
    
    # Read partials
    home_content = read_file('partials/home.html')
    cv_content = read_file('partials/cv.html')
    activities_content = read_file('partials/activities.html')
    
    # Remove section tags from partials (they'll be wrapped in the main sections)
    home_content = home_content.replace('<!-- ===== Home Section Start ===== -->', '').replace('<!-- ===== Home Section End ===== -->', '')
    cv_content = cv_content.replace('<!-- ===== About Section Start ===== -->', '').replace('<!-- ===== About Section End ===== -->', '')
    activities_content = activities_content.replace('<!-- ===== activities Section Start ===== -->', '').replace('<!-- ===== activities Section End ===== -->', '')
    
    # Replace the placeholder divs with actual content
    index_content = index_content.replace(
        '<div id="home-section"></div>',
        home_content.strip()
    )
    
    index_content = index_content.replace(
        '<div id="cv-section"></div>',
        cv_content.strip()
    )
    
    index_content = index_content.replace(
        '<div id="activities-section"></div>',
        activities_content.strip()
    )
    
    # Remove the partials-loader.js script reference
    index_content = index_content.replace(
        '<script src="js/partials-loader.js"></script>\n  ',
        ''
    )
    
    # Add a comment at the top
    standalone_comment = """<!-- 
  ============================================
  STANDALONE VERSION - Generated by build.py
  This file contains all partials inlined
  Can be opened directly without a server
  ============================================
-->
"""
    
    # Insert comment after DOCTYPE
    index_content = index_content.replace(
        '<!DOCTYPE html>\n',
        '<!DOCTYPE html>\n' + standalone_comment
    )
    
    # Write the standalone version
    output_path = 'index-standalone.html'
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(index_content)
    
    print(f"✅ Created: {output_path}")
    print(f"📦 File size: {len(index_content)} bytes")
    print("ℹ️  This file can be opened directly in a browser without a server")
    
    return output_path

if __name__ == '__main__':
    build_standalone()
